mkdir -p "$HOME/.config/zsh"
ln -sf "$HOME/dotfiles/zsh/.zshenv" "$HOME"
ln -sf "$HOME/dotfiles/zsh/.zshrc" "$HOME/.config/zsh"
ln -sf "$HOME/dotfiles/zsh/aliases" "$HOME/.config/zsh/aliases"
rm -rf "$HOME/.config/zsh/external"
ln -sf "$HOME/dotfiles/zsh/external" "$HOME/.config/zsh"
ln -sf "$HOME/dotfiles/bat" "$HOME/.config"
ln -sf "$HOME/dotfiles/nvim" "$HOME/.config"
ln -sf "$HOME/dotfiles/ranger" "$HOME/.config"
mkdir -p "$HOME/.config/sublime-text/Packages"
ln -sf "$HOME/dotfiles/sublime-text/User" "$HOME/.config/sublime-text/Packages"
ln -sf "$HOME/dotfiles/sublime-text/Dracula\ Pro" "$HOME/.config/sublime-text/Packages"
