#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    # My Configuration
    guifont = "MonoLisa:h16"
    enable_cursorline = true
    enable_cursorcolumn = true
    enable_tabline_filetype_icon = true
    filetree_direction = "left"
    default_indent = 4

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 60

# My layers
[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#c'
# enable_clang_syntax_highlight = true

[[layers]]
name = 'ctrlp'
enable = '!has("nvim")'

[[layers]]
name = 'telescope'
enable = 'has("nvim")'

[[layers]]
name = 'lsp'
enabled_clients = ['clangd']
filetypes = [ 'c', 'cpp' ]

[[layers]]
name = 'treesitter'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'VersionControl'

# [[layers]]
# name = 'checkers'
# enable = false
# My custom stuff
# [[custom_plugins]]
# repo = "NLKNguyen/papercolor-theme"
# merged = 0
